# Generated by Django 4.0.5 on 2022-06-08 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='course_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
