# Generated by Django 4.0.5 on 2022-06-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_children_lessons_remove_lesson_course_and_more'),
        ('courses', '0003_alter_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='root_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
