# Generated by Django 4.0.5 on 2022-06-28 05:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_root_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_per_lesson',
            field=models.IntegerField(default=5, validators=[courses.models.validate_points]),
        ),
    ]
