# Generated by Django 4.0.5 on 2022-06-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_root_lesson'),
        ('lessons', '0002_remove_lesson_children_lessons_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='children',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
