# Generated by Django 4.0.5 on 2022-06-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['level']},
        ),
    ]
